name: MLenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - pip:      
      - numpy==1.24.1
      - torch
      - torchvision
      - torchaudio 
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - matplotlib==3.7.5
      - wandb==0.19.7
      - -e .